<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>Image Translate</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="css/web.css">
    </head>

    <body class="bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="text-center">Image Translate: Quickly translate your images</h1>
                    <div class="file-upload-controls">
                        <div class="language-select-div">
                            <label for="language-src-select">Please select the source language.</label>
                            <select id="language-src-select">
                                <option value="english">English</option>
                                <option value="french">French</option>
                                <option value="chinese">Chinese</option>
                            </select>
                            <label for="language-dest-select">Please select the destination language.</label>
                            <select id="language-dest-select">
                                <option value="english">English</option>
                                <option value="french">French</option>
                                <option value="chinese">Chinese</option>
                            </select>
                        </div><!-- end language-select-div -->
                    </div><!-- end file-upload-controls -->

                    <div class="file-upload">
                        <div class="image-upload-wrap">
                            <input class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*, .pdf" />
                            <div class="drag-text">
                                <h3>Drag and drop a file or select add Image</h3>
                            </div><!-- end drag-text -->
                        </div><!-- end image-upload-wrap -->

                        <div class="file-upload-content">
                            <canvas id="myCanvas" width="1000" height="1000">
                                <img class="file-upload-image" src="#" id="myImage" max-width="500" max-height="500">
                            </canvas>
                            <div class="image-title-wrap">
                                <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                                <div class="ocr-result" id="result">
                                    <span class="progress-msg" id="progress"></span>
                                    <br><h6 class="ocr-result">OCR Result:</h6>
                                </div>
                            </div><!-- end image-title-wrap -->
                        </div><!-- end file-upload-content -->
                    </div><!-- end file-upload -->
                </div> <!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->

        <script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script src="js/fabric.js"></script>
        <script src="js/tesseract.js"></script>
        <script src="js/web.js"></script>
        <script src="https://cdn.rawgit.com/naptha/tesseract.js/0.2.0/dist/tesseract.js"></script>

        <script>
            //imageTranslateApp variable is global and we'll use it to store state/modify the page
            imageTranslateApp = initializeImageTranslateApp();
        </script>

        <footer id="footer" class="text-center">
            Project &copy;2019 Shiyun Huang, Brandon Foltz, Choekgi Kalsang, Dennis Uritsky, Kaitlin O'Malley, Stephen Epler, Olivia Chen, Binh Nguyen
        </footer>
    </body>
</html>
