<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Image Translate</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="css/web.css">
    </head>
    <body class="bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="text-center">Image Translate: Quickly translate your images</h1>
                    <div class="file-upload-controls">
                        <div class="instructions">
                            <ul>
                                <li>Select the source language of your image/pdf and the destination language you wish to translate to.</li>
                                <li>For best results, use a clear image with horizontal text and select the source language (rather than auto) if you know it.</li>
                            </ul>
                        </div>
                        <div class="language-select-div">
                            <label for="language-src-select"><b>Source Language</b></label>
                            <select id="language-src-select">
                                <option value="auto">Auto (Latin Text)</option>
                                <option value="chinese_simplified">Chinese (Simplified)</option>
                                <option value="chinese_traditional">Chinese (Traditional)</option>
                                <option value="czech">Czech</option>
                                <option value="danish">Danish</option>
                                <option value="dutch">Dutch</option>
                                <option value="english">English</option>
                                <option value="finnish">Finnish</option>
                                <option value="french">French</option>
                                <option value="german">German</option>
                                <option value="hebrew">Hebrew</option>
                                <option value="indonesian">Indonesian</option>
                                <option value="italian">Italian</option>
                                <option value="japanese">Japanese</option>
                                <option value="korean">Korean</option>
                                <option value="polish">Polish</option>
                                <option value="portuguese">Portuguese</option>
                                <option value="russian">Russian</option>
                                <option value="spanish">Spanish</option>
                                <option value="swedish">Swedish</option>
                                <option value="turkish">Turkish</option>
                            </select>
                            <br/>
                            <label for="language-dest-select"><b>Destination Language</b></label>
                            <select id="language-dest-select">
                                <option value="english">English (Default)</option>
                                <option value="arabic">Arabic</option>
                                <option value="chinese_simplified">Chinese (Simplified)</option>
                                <option value="chinese_traditional">Chinese (Traditional)</option>
                                <option value="czech">Czech</option>
                                <option value="danish">Danish</option>
                                <option value="dutch">Dutch</option>
                                <option value="finnish">Finnish</option>
                                <option value="french">French</option>
                                <option value="german">German</option>
                                <option value="hebrew">Hebrew</option>
                                <option value="indonesian">Indonesian</option>
                                <option value="italian">Italian</option>
                                <option value="japanese">Japanese</option>
                                <option value="korean">Korean</option>
                                <option value="polish">Polish</option>
                                <option value="portuguese">Portuguese</option>
                                <option value="russian">Russian</option>
                                <option value="spanish">Spanish</option>
                                <option value="swedish">Swedish</option>
                                <option value="turkish">Turkish</option>
                            </select>
                        </div>
                        <!-- end language-select-div -->
                    </div>
                    <!-- end file-upload-controls -->
                    <div class="file-upload">
                        <div class="image-upload-wrap">
                            <input class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*, .pdf" />
                            <div class="drag-text">
                                <h3>Drag and drop a file or select add Image</h3>
                            </div>
                            <!-- end drag-text -->
                        </div>
                        <!-- end image-upload-wrap -->
                        <div class="file-upload-content">
                            <div class="text-rendering-controls">
                                <button type="button" onclick="toggleRenderedText(this)" class="toggle-text">Hide Rendered Text</button>
                            </div>
                            <canvas id="myCanvas" width="1000" height="1000">
                                <img class="file-upload-image" src="#" id="myImage" max-width="500" max-height="500">
                            </canvas>
                            <div class="image-title-wrap">
                                <button type="button" class= "translate-image" id="translateButton">Translate!!!</button>
                                <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                                <div class="pdf-buttons">
                                    <button id="pdf-prev">Previous</button>
                                    <button id="pdf-next">Next</button>
                                </div>
                                <div class="ocr-result" id="result">
                                    <span class="progress-msg" id="progress"></span>
                                    <br>
                                    <h6 class="ocr-result">OCR Result:</h6>
                                </div>
                            </div>
                            <!-- end image-title-wrap -->
                        </div>
                        <!-- end file-upload-content -->
                    </div>
                    <!-- end file-upload -->
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
        <script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script src="js/fabric.js"></script>
        <script src="js/tesseract.js"></script>
        <script src="js/web.js"></script>
        <script src="https://cdn.rawgit.com/naptha/tesseract.js/0.2.0/dist/tesseract.js"></script>
        <script src="js/pdf.js"></script>
        <script src="js/pdf.worker.js"></script>
        <script>
            //imageTranslateApp variable is global and we'll use it to store state/modify the page
            imageTranslateApp = initializeImageTranslateApp();
        </script>
        <footer id="footer" class="text-center">
            Project &copy;2019 Shiyun Huang, Brandon Foltz, Choekgi Kalsang, Dennis Uritsky, Kaitlin O'Malley, Stephen Epler, Olivia Chen, Binh Nguyen
        </footer>
    </body>
</html>